### ISSUE TITLE
Add serbian language in readme file

### ISSUE THREAD

**Issue by kelsa-pi** [barseghyanartur/transliterate#27]
Add serbian language in readme

Serbian language pack: transliterate/src/transliterate/contrib/languages/sr/

**Comment by barseghyanartur** [comment]
@kelsa-pi:

Hey, I checked the code. It does seem working, however since it doesn't contain tests, I didn't add it to the readme (now added).

Do you think you could add some tests (so that it changes from pre-alpha to alpha)?

**Comment by kelsa-pi** [comment]
@barseghyanartur
>> Do you think you could add some tests (so that it changes from pre-alpha to alpha)?
OK

**Comment by kelsa-pi** [comment]
@barseghyanartur
I think you can close this issue.
Can you change status for serbian language in readme?
[Tests for serbian language ](https://github.com/barseghyanartur/transliterate/pull/30)
[More tests for serbian language ](https://github.com/barseghyanartur/transliterate/pull/31)
[Test serbian pangram transliteration ](https://github.com/barseghyanartur/transliterate/pull/36)
