### ISSUE TITLE
Georgian language problem

### ISSUE THREAD

**Issue by ninodoghonadze** [barseghyanartur/transliterate#41]
Hi. Thanks for developing this tool. My hope is I can use it with my ugly huge dataset.

I am very new to python. I have the version of Python 2.7.13 and am running on Python Command Line.
When I run: 
>>> from transliterate import translit
>>> text = "Lorem ipsum dolor sit amet"
>>> print(translit(text, 'ka'))
I get this error:

"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\ArcGIS10.5\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-4: character maps to <undefined>"
I have tried extending with .encoding("utf-8") and .encoding("utf-16"). It is returning strange characters. Is there any way of fixing this.

Thanks,
Nino

**Comment by skoval00** [comment]
I can't reproduce your issue with Python 2.7.12.
```
from transliterate import translit
text = "Lorem ipsum dolor sit amet"
print(translit(text, 'ka'))
ლორემ იპსუმ დოლორ სით ამეთ
```

Try to check if this code raises any exceptions in your Python Command Line (REPL)
```
translation_table = {65: 4304, 66: 4305, 67: 4330, 68: 4307, 69: 4308, 70: 4324, 71: 4306, 72: 4336, 73: 4312, 74: 4319, 75: 4313, 76: 4314, 77: 4315, 78: 4316, 79: 4317, 80: 4318, 81: 4325, 82: 4320, 83: 4321, 84: 4322, 85: 4323, 86: 4309, 88: 4334, 89: 4327, 90: 4310, 97: 4304, 98: 4305, 99: 4330, 100: 4307, 101: 4308, 102: 4324, 103: 4306, 104: 4336, 105: 4312, 106: 4335, 107: 4313, 108: 4314, 109: 4315, 110: 4316, 111: 4317, 112: 4318, 113: 4325, 114: 4320, 115: 4321, 116: 4311, 117: 4323, 118: 4309, 119: 4332, 120: 4334, 121: 4327, 122: 4310}
u'lorem ipsum dolor sit amet'.translate(translation_table)
```

**Comment by barseghyanartur** [comment]
@ninodoghonadze:

Try to specify encoding in the beginning of the your python module(s).

```python
# -*- coding: utf-8 -*-

from transliterate import translit
text = "Lorem ipsum dolor sit amet"
print(translit(text, 'ka'))
ლორემ იპსუმ დოლორ სით ამეთ
```
