### ISSUE TITLE
cyrillic

### ISSUE THREAD

**Issue by big-vl** [barseghyanartur/transliterate#54]
UnicodeEncodeError: 'ascii' codec can't encode character '\xeb' in position 4: ordinal not in range(128)

ё

**Comment by barseghyanartur** [comment]
Can't reproduce it. On both Python 2.7 and 3.6.

===py27===

In [1]: from transliterate import translit

In [2]: s = u'ё'

In [3]: translit(s, language_code='ru', reversed=True)
Out[3]: u'e'

In [4]: translit(s, language_code='ru')
Out[4]: u'\u0451'

===py36===

In [1]: from transliterate import translit


In [2]: s = 'ё'


In [3]: translit(s, language_code='ru', reversed=True)

Out[3]: 'e'

In [4]: translit(s, language_code='ru')

Out[4]: 'ё'

===

**Comment by big-vl** [comment]
specifically ё parse text
```
        s = 'ëина'
        x = translit(s, language_code='ru', reversed=True)
        print(str(x).encode('utf-8')) 
```
out: b'\xc3\xabina'

**Comment by barseghyanartur** [comment]
```x``` is already a string. what are you trying to achieve by
```str(x).encode('utf-8')```.

For me the following works:

===py36===

In [1]: from transliterate import translit


In [2]: s = 'ëина'


In [3]: x = translit(s, language_code='ru', reversed=True)


In [4]: print(x)

ëina

In [5]: x

Out[5]: 'ëina'

===

**Comment by big-vl** [comment]
i am not use terminal Cyrillic Russian text, i view:
UnicodeEncodeError: 'ascii' codec can't encode character '\xeb' in position 4: ordinal not in range(128)

technical work dont use look russian lang
!bug translite

**Comment by barseghyanartur** [comment]
@big-vl:

Please, be more specific. What do you use to view? It might be an error in your viewer.

**Comment by barseghyanartur** [comment]
It does work in the browser (using Jupyter).

Check this:

https://gist.github.com/barseghyanartur/0a1c7ff065a744649e7f142dbf79c5a3

**Comment by big-vl** [comment]
I need transliteration, the specific one doesn’t convert it, it does not see it as a symbol, my code above proves it.
I use the terminal without the support of Russian and specific letters, I see the error indicated above, or I have to use a decode, which is detrimental in my terms of reference, you can of course use text replacement, which is also not desirable, since I can not catch all the specific letters

**Comment by barseghyanartur** [comment]
I see. I'll fix that soon. The letter ``ë`` is missing in the mappings and shall be added.

**Comment by barseghyanartur** [comment]
@big-vl:

Hey, an update. Although the character you've used looks like russian ``jo`` letter, it isn't.

```
In [1]: from transliterate import translit                                                                                                            

In [2]: s = 'ëина'  # This one is yours 

In [3]: x = translit(s, language_code='ru', reversed=True)                                                                                            

In [4]: x.encode()                                                                                                                                    
Out[4]: b'\xc3\xabina'

In [5]: s = 'ё'  # This one is correct

In [6]: x = translit(s, language_code='ru', reversed=True)                                                                                            

In [7]: x                                                                                                                                             
Out[7]: 'e'

In [8]: s = 'ёжик'  # This one is correct

In [9]: x = translit(s, language_code='ru', reversed=True)                                                                                            

In [10]: x                                                                                                                                            
Out[10]: 'ezhik'
```

Check the [Wikipedia](https://en.wikipedia.org/wiki/Romanization_of_Russian#Transliteration_table).

**Comment by big-vl** [comment]
thanks, you best programming, respect! :)

**Comment by big-vl** [comment]
you upload new version to pip?

**Comment by barseghyanartur** [comment]
@big-vl:

No, there wasn't any update. What I meant is your initial text contains wrong characters. Although the character you've used looks like Cyrillic ``jo`` letter, it isn't. That's the core of the problem.

**Comment by big-vl** [comment]
everything is correct, I for this also deduced through decode that it is necessary to fix what would work for me, as I understand the mapping truple;)
