### ISSUE TITLE
Strange behavior of slugify

### ISSUE THREAD

**Issue by aisayko** [barseghyanartur/transliterate#6]
>>> slugify(u'Blaa')
    u'blaa'
    >>> slugify(u'Par')
    >>> slugify(u'Париж')
    u'parizh'
    >>> slugify(u'Зфкшы')
    u'zfkshy'
    >>> slugify(u'Paris')
    >>>

Strange, but in some cases slugify() return None

**Comment by AndrewBurdyug** [comment]
Just add slugify for 'en', people want to use simple form:

```python
 slugify(s)
```
- no metter what is it 's': 'ru' or 'en' string, if 'en' string you need just normilize string(replace blanks to dashes, lowerize etc).

**Comment by barseghyanartur** [comment]
@AndrewBurdyug:

Thanks for the extensive suggestion! I'll take a look at it as soon as possible.

**Comment by AndrewBurdyug** [comment]
thank you we will wait :)

**Comment by barseghyanartur** [comment]
@AndrewBurdyug:

I don't remember when did I fix that, but at the moment `slugify` works properly on latin texts. Therefore, I'm closing the issue.
