### ISSUE TITLE
Transliteration of Greek language

### ISSUE THREAD

**Issue by Wtower** [barseghyanartur/transliterate#8]
Hi, thanks for the nice package.

I would like to make a few points for the greek language if I may, assuming that the goal of the code is to provide readability rather than keyboard mapping. For version 1.7.3, the transliterated string of the greek alphabet using is:
### Small letters

```
>>> translit('αβγδεζηθικλμνξοπρστυφχψω', reversed=True)
'abgdezhuiklmnxoprstyfchpsw'
```
- η should be i (but not h) (pos: 7)
- θ should be th (but not u) (pos: 8)
- ω should be o (but not w) (pos: 24)
### Capital letters

```
>>> translit('ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ', reversed=True)
'ABGDEZHUIKLMNXOPRSTYFCHPSW'
```
- Η should be I (but not H) (pos: 7)
- Θ should be TH (but not U) (pos: 8)
- Ω should be O (but not W) (pos: 24)
### Other letters (not currently transliterated)

```
>>> translit('ςάέήίύόώϊϋΐΰ', reversed=True)
'ςάέίύήόώϊϋΐΰ'
```
- should be 'saeiiyooiyiy'

**Comment by barseghyanartur** [comment]
@Wtower 

Hey, thanks for reporting this. Did you check it also here?

http://en.wikipedia.org/wiki/Romanization_of_Greek

I'm quite busy at the moment with other things. If you do have some spare time, you could make the necessary changes and submit a pull request. Otherwise, I would do it myself, but some time later.

**Comment by Wtower** [comment]
Nice link. It happens that the recommendations above are consistent with it as far as I can tell.

I certainly understand about you being busy. I tried to fix the issue myself in file https://github.com/barseghyanartur/transliterate/blob/master/src/transliterate/contrib/languages/el/data/python32.py.

The letter `'θ'` for instance is in both `reversed_specific_mapping` and `pre_processor_mapping`. Removing the first one does not seem to make it work properly, as I would expect.

If you could only give me a hint about this, the other letters are not a problem.

**Comment by Romamo** [comment]
I refactored greek mappings https://github.com/Romamo/transliterate
