### ISSUE TITLE
Are you interested in transliteration from languages written in modified/extended Latin scripts?

### ISSUE THREAD

**Issue by eldang** [barseghyanartur/transliterate#9]
I'm working with Azeri addresses at the moment, and need to be able to compare between names written in Azeri (e.g. `Bakı şəhəri`) and their ASCII transliterations (this one would be `Baku shahari`), because even some government-provided shapefiles use the ASCIIfied versions.  It looks like the best way for me to do this will be to use this package and make a custom language file.  _Iff_ I can find a standard, consistently-used transliteration,  would you want me to submit it for inclusion?

I'm hedging because I'm not certain that such a thing exists, so I might just have to make something that works with the files I have, and I wouldn't want to submit that because it won't be reliable for arbitrary data sources.

**Comment by barseghyanartur** [comment]
@eldang 

What's needed for that is something similar to this:

- http://en.wikipedia.org/wiki/Romanization_of_Russian#Transliteration_table

If you get the information, I can assist you in making a plugin and will certainly accept your pull request. Tests do make part of the requirements.

**Comment by eldang** [comment]
Thanks!  Unfortunately, I'm neither finding a reference list nor the consistency I was hoping for between different Azeri-ASCII transliterations.  I think I will still use this for my own data, but it looks like it won't be broadly enough applicable to make sense to include in this project.
